# Generated by Django 6.0.3 on 2026-04-02 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_games(apps, schema_editor):
    Game = apps.get_model("core", "Game")
    catalog = [
        {
            "slug": "quiz-fracoes",
            "title": "Quiz de Fracoes",
            "description": "Perguntas rapidas para revisar fracoes e equivalencias.",
            "instructions": "Responda em sequencia e tente superar sua melhor pontuacao.",
            "experience_type": "quiz",
            "estimated_minutes": 6,
            "status": "published",
        },
        {
            "slug": "memoria-ciencias",
            "title": "Memoria de Ciencias",
            "description": "Combine conceitos e imagens em uma rodada curta.",
            "instructions": "Vire cartas, encontre pares e mantenha o foco nos conceitos.",
            "experience_type": "memoria",
            "estimated_minutes": 7,
            "status": "published",
        },
        {
            "slug": "sequencia-historica",
            "title": "Sequencia Historica",
            "description": "Organize eventos em ordem cronologica.",
            "instructions": "Arraste mentalmente os eventos e avance por fases curtas.",
            "experience_type": "sequencia",
            "estimated_minutes": 8,
            "status": "published",
        },
        {
            "slug": "palavras-geografia",
            "title": "Palavras da Geografia",
            "description": "Descubra termos-chave ligados a mapas e territorio.",
            "instructions": "Complete pistas, forme palavras e acompanhe seu progresso.",
            "experience_type": "palavras",
            "estimated_minutes": 5,
            "status": "published",
        },
        {
            "slug": "logica-padroes",
            "title": "Logica dos Padroes",
            "description": "Resolva desafios curtos de logica e repeticao.",
            "instructions": "Observe os padroes, escolha a melhor continuacao e pontue.",
            "experience_type": "logica",
            "estimated_minutes": 9,
            "status": "published",
        },
    ]
    for item in catalog:
        Game.objects.update_or_create(slug=item["slug"], defaults=item)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userprofile_preferences_and_community_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("instructions", models.TextField()),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("memoria", "Memoria"),
                            ("sequencia", "Sequencia"),
                            ("palavras", "Palavras"),
                            ("logica", "Logica"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estimated_minutes", models.PositiveIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["title", "id"]},
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("progress", models.PositiveIntegerField(default=0)),
                ("played_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.game",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-played_at", "-id"]},
        ),
        migrations.RunPython(seed_games, migrations.RunPython.noop),
    ]
